#!/bin/bash

error () {
  echo $1
  echo "do sumpin liek"
  echo "  mln \${real} \${link} '\${opts}' (think \`cp existing new\`)"
  echo "v0.1 copyright michael fairhurst"
  exit $2
}

if [ -z "$1" ]
then
  error "you no has a REAL" 1
fi

if [ -z "$2" ]
then
  error "you no has a LINK" 2
fi

REAL=$(readlink -f "$1")
REAL_BASE=$(basename "$REAL")
LINK=$2
OPTS=$3

if [[ -d "$LINK" ]]
then
  LINK=$LINK/$REAL_BASE
fi

if [ -e "$REAL" ]
then
  :
else
  error "your \${real} doesnt exist mang" 3
fi

if [ -e "$LINK" ]
then
  error "your \${link} exists mang" 4
fi

LINK_DIR=$(dirname "$LINK")
LINK_BASE=$(basename "$LINK")

cd $LINK_DIR && ln -T $REAL $LINK_BASE $OPTS && exit 0

error "shit something went wrong and I aint gotta clue what" 4
