#!/bin/bash

if [ -z "$1" ]
then
  echo "you no has a REAL"
  echo "do sumpin liek"
  echo "  mln \${real} \${link} '\${opts}' (think cp from to)"
  exit 1
fi

if [ -z "$2" ]
then
  echo "you no has a LINK"
  echo "do sumpin liek"
  echo "  mln \${real} \${link} '\${opts}' (think cp from to)"
  exit 2
fi

REAL=$(readlink -f "$1")
REAL_BASE=$(basename "$REAL")
LINK=$2
OPTS=$3

if [[ -d "$LINK" ]]
then
  LINK=$LINK/$REAL_BASE
fi

if [ -e "$REAL" ]
then
  :
else
  echo "your \${real} doesnt exist mang"
  echo "do sumpin liek"
  echo "  mln \${real} \${link} '\${opts}' (think cp from to)"
  exit 3
fi

if [ -e "$LINK" ]
then
  echo "your \${link} exists mang"
  echo "do sumpin liek"
  echo "  mln \${real} \${link} '\${opts}' (think cp from to)"
  exit 4
fi

LINK_DIR=$(dirname "$LINK")
LINK_BASE=$(basename "$LINK")

#echo "cd $LINK_DIR && ln -T $REAL $LINK_BASE $OPTS && exit 0"
#exit 0
cd $LINK_DIR && ln -T $REAL $LINK_BASE $OPTS && exit 0

echo "shit something went wrong and I aint gotta clue what"
exit 4
